apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: nginx

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
      - name: dockerdemo
        image: shanmukh29/dockerdemo:v1.0.1
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
        - containerPort: 80
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
