apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx

  ports:
    - protocol: TCP
      port: 7104
      targetPort: 7104
      nodePort: 7104


  type: NodePort
