apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx

  ports:
    - protocol: HTTP
      port: 80
      targetPort: 30428
      nodePort: 30428


  type: NodePort
